name: linux-x64-cpu-gcc
on: [push, pull_request]
jobs:
    linux-gcc-py2:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: install
          run: python2 -m pip install -v -e . &&
               python2 -m pip install mxnet --pre &&
               python2 -m pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html &&
               python2 -m pip install coveralls
        - name: test
          run: python2 -m nosetests -s --with-coverage
