name: windows-x64-vs2019
on: [push, pull_request]
jobs:
    windows-x64-py2:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: install
          run: python2 -m pip install -v -e . &&
               python2 -m pip install mxnet --pre &&
               python2 -m pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html &&
               python2 -m pip install coveralls nosetests
        - name: cpu-test
          run: python2 -m nosetests -s --with-coverage
        - name: gpu-test
          run: python2 -m nosetests tests/gpu/test_gpu.py -s --with-coverage
    windows-x64-py3:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: install
          run: python3 -m pip install -v -e . &&
               python3 -m pip install mxnet --pre &&
               python3 -m pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html &&
               python3 -m pip install coveralls nosetests
        - name: cpu-test
          run: python3 -m nosetests -s --with-coverage
        - name: gpu-test
          run: python3 -m nosetests tests/gpu/test_gpu.py -s --with-coverage
